### PR TITLE
Add dropbox support

### PR DESCRIPTION
**Pull request by webrgp**
Hi Richard,

So this is working code. I was backing up just the config file (42kb) while I was implementing and testing the Dropbox implementation and everything worked end-to-end.

But when I've cranked up to a bigger backup size (700mb), php timed out with a 504 (the upload took longer than the session max time), but after waiting a while, the backup did upload.

What do you think would be a better solution? Create a Craft Task?

### CODE REVIEW

**Comment by rtrudel** [comment]
Hi. It would be a good idea to use Craft tasks indeed. But you said it worked anyway?

**Comment by rtrudel** [comment]
Just tested. Very nice addition! Thanks! Perhaps my next step will be to integrate GoogleDrive and S3 destinations.

Noticed a "problem". `composer update` is required in order to get some modules (as dropbox). Any idea to avoid this?

**Comment by webrgp** [comment]
Quick thing: I am exploring using Tasks to do the upload. When the final file is too big, the dropbox upload times-out in the front end, but the upload still going behind the scenes. So, expect another pull request soon ;-)

**Comment by rtrudel** [comment]
Nice! I sent you an email about something tricky, if you did not got it, I can transcript here.

**Pull request merged**
